### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by robertdj** [aryoda/R_enumerations#4]
Hi

Thanks for great package! 

Is it possible to make a release? I would like to specify the version I'm using when installing from `remotes`. 

Thanks!

**Comment by aryoda** [comment]
Yes, I can publish a (github) release for every stable version.

API-breaking changes may still occur since I am not yet satisfied with the function names and usability (R is beast regarding enumerations with good usability).

Is a github release OK for you?

I am not planing to publish the package at CRAN until it is stable (regarding the API)...

**Comment by robertdj** [comment]
A GitHub release sounds great! Then it should be possible to install specific versions with `devtools` or `remotes` :-)

**Comment by aryoda** [comment]
I have created a release now and updated the installation instructions of the readme "front page".

For other readers of this issue: To install this first release use

```R
devtools::install_github("aryoda/R_enumerations@v0.3.0-beta")`
```
Thanks for your helpful propsal!

Please let me know if you have problems to install the release (otherwise I will close the issue in a few days).

**Comment by robertdj** [comment]
It works for me :-) 

Thank you!
